name: djj

services:
  djj:
    image: lzylipu/djj:latest
    container_name: djj
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - djj-data:/data
      - /path/to/videos1:/videos/dance:ro
      - /path/to/videos2:/videos/funny:ro

volumes:
  djj-data:
